In [1]:
print('Hello, Lightning World!')
# import asyncio
# import os
# import json
# from uuid import uuid4
# from dotenv import load_dotenv
from huggingface_hub import login
from vllm import AsyncEngineArgs, AsyncLLMEngine, SamplingParams

Hello, Lightning World!
INFO 04-10 10:04:14 [__init__.py:239] Automatically detected platform cuda.

In [2]:
engine = AsyncLLMEngine.from_engine_args(
            AsyncEngineArgs(
                model="meta-llama/Llama-3.1-8B-Instruct",
                trust_remote_code=True,
                quantization="bitsandbytes",
                max_model_len=10000,
                gpu_memory_utilization=0.7,
            )
        )

INFO 04-10 10:04:24 [config.py:600] This model supports multiple tasks: {'generate', 'embed', 'reward', 'classify', 'score'}. Defaulting to 'generate'.
WARNING 04-10 10:04:24 [config.py:679] bitsandbytes quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 04-10 10:04:24 [config.py:1780] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 04-10 10:04:25 [core.py:61] Initializing a V1 LLM engine (v0.8.3) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=10000, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=meta-llama/Llama-3.1-8B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 04-10 10:04:26 [utils.py:2413] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7ff5293769e0>
INFO 04-10 10:04:26 [parallel_state.py:957] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-10 10:04:26 [cuda.py:221] Using Flash Attention backend on V1 engine.
INFO 04-10 10:04:26 [gpu_model_runner.py:1258] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
WARNING 04-10 10:04:26 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 04-10 10:04:26 [loader.py:1155] Loading weights with BitsAndBytes quantization. May take a while ...
INFO 04-10 10:04:27 [weight_utils.py:265] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

INFO 04-10 10:04:30 [gpu_model_runner.py:1273] Model loading took 5.3422 GiB and 3.358956 seconds
INFO 04-10 10:04:38 [backends.py:416] Using cache directory: /home/zeus/.cache/vllm/torch_compile_cache/3508202190/rank_0_0 for vLLM's torch.compile
INFO 04-10 10:04:38 [backends.py:426] Dynamo bytecode transform time: 8.18 s
INFO 04-10 10:04:39 [backends.py:115] Directly load the compiled graph for shape None from the cache
INFO 04-10 10:04:45 [monitor.py:33] torch.compile takes 8.18 s in total
INFO 04-10 10:04:47 [kv_cache_utils.py:578] GPU KV cache size: 42,960 tokens
INFO 04-10 10:04:47 [kv_cache_utils.py:581] Maximum concurrency for 10,000 tokens per request: 4.30x
INFO 04-10 10:05:28 [gpu_model_runner.py:1608] Graph capturing finished in 41 secs, took 5.97 GiB
INFO 04-10 10:05:28 [core.py:162] init engine (profile, create kv cache, warmup model) took 58.03 seconds

In [3]:
prompt = "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\nYou are a professional PostgreSQL expert who generates optimized, correct SQL queries from natural language questions based on the schema provided. \nThink step by step to break down the user's request, reason about how to join and filter relevant tables, and form an efficient SQL query. \nUse Common Table Expressions (CTEs) when needed for readability and performance. Always use explicit JOINs.\n\nSchema Format:\n- TableName (Row count)\n  - column_name: data_type [PK|FK → referenced_table.column], [NOT NULL]\n\nInstructions:\n- Think aloud step by step and genertate.\n- Explain any assumptions briefly.\n- At the end, return the one final SQL query inside a single ```sql code block.\n- Do not include markdown outside the code block.\n- If the query includes unknown terms or entities not found in the schema, respond only with:\n\n```sql\nSELECT 'Unable to generate query: entity not found in schema.' AS message;\n```\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n## Schema\n### departments (9 rows)\n- dept_no: character (PK), NOT NULL\n- dept_name: character varying, NOT NULL\n\n### dept_emp (331041 rows)\n- emp_no: integer (PK) (FK → employees.emp_no), NOT NULL\n- from_date: date, NOT NULL\n- to_date: date, NOT NULL\n- dept_no: character (PK) (FK → departments.dept_no), NOT NULL\n\n### employees (299509 rows)\n- emp_no: integer (PK), NOT NULL\n- birth_date: date, NOT NULL\n- gender: USER-DEFINED\n- hire_date: date, NOT NULL\n- first_name: character varying, NOT NULL\n- last_name: character varying, NOT NULL\n\n### dept_manager (24 rows)\n- emp_no: integer (PK) (FK → employees.emp_no), NOT NULL\n- from_date: date, NOT NULL\n- to_date: date, NOT NULL\n- dept_no: character (PK) (FK → departments.dept_no), NOT NULL\n\n### salaries (2839079 rows)\n- emp_no: integer (PK) (FK → employees.emp_no), NOT NULL\n- salary: integer, NOT NULL\n- from_date: date (PK), NOT NULL\n- to_date: date, NOT NULL\n\n### titles (442547 rows)\n- emp_no: integer (PK) (FK → employees.emp_no), NOT NULL\n- from_date: date (PK), NOT NULL\n- to_date: date\n- title: character varying (PK), NOT NULL\n\n\n## Query Request\nWhich departments have more than 70% of employees of one gender (current employees only)? Show dept_name, gender, and percentage.\n<|eot_id|><|start_header_id|>assistant<|end_header_id|>"

In [4]:
params = SamplingParams(
        top_k=1,
        temperature=0.8,
        max_tokens=1000,
        stop=["<|eot_id|>"],
    )

In [6]:
output = engine.generate(prompt, params, "user_id")

In [11]:
async for output in output:
        print(output.outputs[0].text)

INFO 04-10 10:07:47 [async_llm.py:228] Added request user_id.






To s


To solve thi


To solve this


To solve this p


To solve this proble


To solve this problem, I w


To solve this problem, I will


To solve this problem, I will brea


To solve this problem, I will break it


To solve this problem, I will break it down i


To solve this problem, I will break it down into


To solve this problem, I will break it down into


To solve this problem, I will break it down into s


To solve this problem, I will break it down into step


To solve this problem, I will break it down into steps:

1


To solve this problem, I will break it down into steps:

1. *


To solve this problem, I will break it down into steps:

1. **Ide


To solve this problem, I will break it down into steps:

1. **Identify t


To solve this problem, I will break it down into steps:

1. **Identify the t


To solve this problem, I will break it down into steps:

1. **Identify the tables an


To solve this problem, I will break it down into steps:

1. **Identify the tables and colum


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns nee


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: W


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We ne


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need t


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `em


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `empl


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employee


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`,


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `d


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_em


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `de


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `dep


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `department


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments`


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tabl


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables t


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get th


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current e


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employe


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their de


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their dep


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departm


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the d


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the departm


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the departme


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We als


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calc


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the p


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the perc


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of emp


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employe


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of o


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gende


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each d


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each depa


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each depar


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each depart


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each departmen


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calc


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the tot


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of emp


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employee


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each d


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each depa


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each departm


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We w


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will use a


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will use a su


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will use a subque


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will use a subquery t


To solve this problem, I will break it down into steps:

1. **Identify the tables and columns needed**: We need to use the `employees`, `dept_emp`, and `departments` tables to get the current employees, their departments, and the department names. We also need to calculate the percentage of employees of one gender in each department.

2. **Calculate the total number of employees in each department**: We will use a subquery to get


To solve this problem, I will break it down into steps:


In [16]:
import asyncio
async def generate_output():
    # Generate the output without streaming
    results = await engine.generate(prompt, params,"asdsad")
    # Extract and print the generated text
    for result in results:
        print(result.outputs[0].text)

# Run the asynchronous function
await generate_output()

TypeError: object async_generator can't be used in 'await' expression